- docusaurus.config.js
- static/robots.txt
> docs: vercelのURLに変更

- docusaurus.config.js
> Twitter:siteの変更

- docusaurus.config.js
> Meta keyword を追加

- docs/app-router/01-building-your-application/08-testing/03-Playwright.md
[Playwright ](https://nextjs.org/docs/app/building-your-application/testing/playwright)の翻訳
Closes #25 
[Playwright _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14019714/Playwright._.Next.js.pdf)
> Docs: Translate Playwright Page

- docs/app-router/index.md
本プロジェクトの信頼度を上げるため、公式ポストのリンクを貼った方がいいかもしれないという話もありましたので、これでいかがでしょうか。ご検討のほどよろしくお願いします。
> Add link to X Post for legitimacy

- docs/app-router/01-building-your-application/08-testing/02-Jest.md
[Jest](https://nextjs.org/docs/app/building-your-application/testing/jest)の翻訳
Closes #24 
[Jest_Next.js 公式ドキュメント日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14003925/Jest_Next.js.pdf)
> Docs: Translate Jest Page 

- docs/app-router/02-api-reference/03-functions/fetch.md
[fetch](https://nextjs.org/docs/app/api-reference/functions/fetch)の翻訳
Closes #36 
[fetch _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14096573/fetch._.Next.js.pdf)
> Docs: Translate fetch Page

- docs/app-router/02-api-reference/03-functions/cookies.md
[cookies](https://nextjs.org/docs/app/api-reference/functions/cookies)の翻訳
Closes #35 
[cookies _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14096927/cookies._.Next.js.pdf)
> Docs: Translate cookies Page

- docs/app-router/02-api-reference/03-functions/next-response.md
[NextResponse](https://nextjs.org/docs/app/api-reference/functions/next-response)の翻訳
closes #44
> #44 Translate nextResponse

- docs/app-router/02-api-reference/03-functions/unstable_cache.md
[unstable_cache](https://nextjs.org/docs/app/api-reference/functions/unstable_cache)の翻訳
Closes #49 
[unstable_cache _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14190082/unstable_cache._.Next.js.pdf)
> Docs: Translate unstable_cache

- docs/app-router/02-api-reference/04-next-config-js/server-actions.md
[serverActions](https://nextjs.org/docs/app/api-reference/next-config-js/serverActions)の翻訳
closes #61
> #61 serverActions

- docs/app-router/01-building-your-application/06-optimizing/06-bundle-analyzer.md
[Bundle Analyzer](https://nextjs.org/docs/app/building-your-application/optimizing/bundle-analyzer)の翻訳
closes #83
> #83 bundle analyzer

- docs/app-router/02-api-reference/04-next-config-js/optimize-package-imports.md
[optimizePackageImports](https://nextjs.org/docs/app/api-reference/next-config-js/optimizePackageImports)の翻訳
Closes #54  
[optimizePackageImports _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14303565/optimizePackageImports._.Next.js.pdf)
> Docs: Translate next.config.js Options / optimizePackageImports

- docs/app-router/02-api-reference/03-functions/generate-static-params.md
[generateStaticParams](https://nextjs.org/docs/app/api-reference/functions/generate-static-params)の翻訳
Closes #40 
[generateStaticParams _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14255620/generateStaticParams._.Next.js.pdf)
> Docs: Translate generateStaticParams

- docs/app-router/01-building-your-application/07-configuring/02-eslint.md
[ESLint](https://nextjs.org/docs/app/building-your-application/configuring/eslint)の翻訳
closes #86
> Translate ESlint

- docs/app-router/04-community/_category_.yaml
- docs/app-router/04-community/contribution-guide.md
- docs/app-router/04-community/index.md
> fix: rm community

- docs/app-router/01-building-your-application/02-data-fetching/index.md
[データフェッチ](https://ja.next-community-docs.dev/docs/app-router/building-your-application/data-fetching/)の最新化及びページ順序を公式と合わせる
closes #81
> #81 Fix Data fetching index page

- docs/app-router/01-building-your-application/11-upgrading/03-version-14.md
[Version 14](https://nextjs.org/docs/app/building-your-application/upgrading/version-14)の翻訳
closes #31
> #31 Version 14

- docs/app-router/03-architecture/supported-browsers.md
[Supported Browsers](https://nextjs.org/docs/architecture/supported-browsers)の翻訳
Closes #67  
[サポートされているブラウザ _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14357423/_.Next.js.pdf)
> Docs: Translate Architecture / Supported Browsers

- docs/app-router/01-building-your-application/06-optimizing/02-videos.md
[Video Optimization](https://nextjs.org/docs/app/building-your-application/optimizing/videos)の翻訳
closes #167
> #167 Translate optimizing video

- docs/app-router/01-building-your-application/05-styling/01-css-modules.md
[CSS Modules](https://nextjs.org/docs/app/building-your-application/styling/css-modules)の翻訳
closes #163
> # 163  Styling / CSS Modules

- docs/app-router/01-building-your-application/07-configuring/05-mdx.md
- docs/app-router/01-building-your-application/07-configuring/index.md
- docs/app-router/01-building-your-application/08-testing/index.md
[Testing](https://nextjs.org/docs/app/building-your-application/testing)
* 下層ページのインデクスを追加
closes #186
> #186 testing indices

- docs/app-router/01-building-your-application/05-styling/index.md
[Styling](https://nextjs.org/docs/app/building-your-application/styling)
* 下層ページのインデクスを追加
closes #184
> #184: Styling add indices

- docs/app-router/02-api-reference/02-file-conventions/instrumentation.md
[File Conventions](https://nextjs.org/docs/app/api-reference/file-conventions)
サイドバーの順番を変更
* instrumentation.js
closes #190
> #190 Fix sidebar position

- docs/app-router/02-api-reference/03-functions/generate-metadata.md
[Functions / Generate-metadata](https://nextjs.org/docs/app/api-reference/functions/generate-metadata)
* サイドバーに表示するタイトルを「generateMetadata」へ修正する
closes #192
> #192 Fix generateMetadata

- docs/app-router/02-api-reference/04-next-config-js/exportPathMap.md
- docs/app-router/02-api-reference/04-next-config-js/turbo.md
- docs/app-router/03-architecture/index.md
- docs/app-router/03-architecture/turbopack.md
Closes #198 
Closes #194  
Closes #195
> fix: Architecture Index Tree And Sidebar Title

- docusaurus.config.js
- package-lock.json
- package.json
Docusaususのプラグインを用いて、検索機能をつけてました
Closes #217
> add-search

- README.md
READMEを更新し、Contributorsを表示するようにしました。
> feat: add contributors img README

- scripts/konjacbot/cp.mts
- scripts/konjacbot/diff.mts
- scripts/konjacbot/dlimg.mts
- scripts/konjacbot/mod.mts
- scripts/konjacbot/pr.mts
- scripts/konjacbot/translate.mts
- scripts/konjacbot/types.mts
- scripts/konjacbot/utils.mts
* R100 Support
* Ignore PR Summray failures.
> polish bot

- scripts/konjacbot/pr.mts
workflowの [`gh pr create` がエラーとなる問題](https://github.com/openstandia/Nextjs-docs-ja/actions/runs/12878803391/job/35905302911#step:12:770)を修正しました。
修正後の動作確認結果は以下です。
https://github.com/openstandia/Nextjs-docs-ja/pull/317
> fix PR script

- Contributing.md
- ラベルルール
- ブランチ戦略・ネーミングルール
を記載しました。
closes #263,#265
> docs: add rules for Contributing.md

- docusaurus.config.js
> chore: update sitemap changefreq #328

- docusaurus.config.js
> chore: update keywords

- docusaurus.config.js
ヘッダーメニューを追加し、様々な情報にアクセスできるように修正
Closes #361
> feat: add header menu #361

- src/css/custom.css
- src/css/index.module.css
- src/pages/index.tsx
> feat: add top page #359
