openstandia/Nextjs-docs-ja

docs/app-router/01-building-your-application/03-rendering/index.md
こんにちは。ドキュメントを読んでいたところ、いくつかのハイパーリンクが誤っていることに気付きました。  
変更内容:
「Client Components」のセクションにおけるリンク先を /docs/app-router/building-your-application/rendering/client-components に修正しました。
「構成パターン」のセクションにおけるリンク先を /docs/app-router/building-your-application/rendering/composition-patterns に修正しました。
「Edge / Node.js ランタイム」のセクションにおけるリンク先を /docs/app-router/building-your-application/rendering/edge-and-nodejs-runtimes に修正しました。
ご確認の上、問題がなければマージをお願いします。
よろしくお願いいたします。
=> ドキュメント内のリンク先を正しいものに更新

docs/app-router/01-building-your-application/08-testing/04-Cypress.md
[Cypress](https://nextjs.org/docs/app/building-your-application/testing/cypress)の翻訳
Closes #26 
[Cypress _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14019715/Cypress._.Next.js.pdf)
=> Docs: Translate Cypress Page

docs/app-router/01-building-your-application/09-deploying/02-static-exports.md
[Static Exports](https://nextjs.org/docs/app/building-your-application/deploying/static-exports)の翻訳
Closes #29  
[静的エクスポート _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14092721/_.Next.js.pdf)
=> Docs: Translate Static Export Page

docs/app-router/02-api-reference/03-functions/generate-image-metadata.md
[generateImageMetadata](https://nextjs.org/docs/app/api-reference/functions/generate-image-metadata)の翻訳
Closes #37 
[generateImageMetadata _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14192369/generateImageMetadata._.Next.js.pdf)
=> Docs: Translate generateImageMetadata

docs/app-router/02-api-reference/03-functions/user-agent.md
[userAgent](https://nextjs.org/docs/app/api-reference/functions/userAgent)の翻訳
Closes #110 
[userAgent _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14188646/userAgent._.Next.js.pdf)
=> Docs: Translate userAgent

docs/app-router/02-api-reference/03-functions/unstable_noStore.md
[unstable_noStore](https://nextjs.org/docs/app/api-reference/functions/unstable_noStore)の翻訳
Closes #50 
[unstable_noStore _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14189994/unstable_noStore._.Next.js.pdf)
=> Docs: Translate unstable_noStore

docs/app-router/01-building-your-application/07-configuring/08-content-security-policy.md
[Content Security Policy](https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy)の翻訳
Closes #91   
[コンテンツセキュリティポリシー _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14219232/_.Next.js.pdf)
=> Docs: Translate Content Security Policy

docs/app-router/02-api-reference/04-next-config-js/pageExtensions.md
[pagesExtensions](https://nextjs.org/docs/app/api-reference/next-config-js/pageExtensions)の翻訳
Closes #56  
[pageExtensions _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14303459/pageExtensions._.Next.js.pdf)
=> Docs: Translatenext.config.js Options / pagesExtensions

docs/app-router/02-api-reference/04-next-config-js/output.md
[output](https://nextjs.org/docs/app/api-reference/next-config-js/output)の翻訳
Closes #55 
[output _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14258351/output._.Next.js.pdf)
=> Docs: Translate next.config.js Options / output

docs/app-router/02-api-reference/03-functions/generate-viewport.md
[generateViewport](https://nextjs.org/docs/app/api-reference/functions/generate-viewport)の翻訳
Closes #41 
[generateViewport _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14256100/generateViewport._.Next.js.pdf)
=> Docs: Translate generateViewport

docs/app-router/02-api-reference/04-next-config-js/logging.md
[logging](https://nextjs.org/docs/app/api-reference/next-config-js/logging)の翻訳
closes #53
=> #53 Translate logging

docs/app-router/02-api-reference/03-functions/generate-sitemaps.md
[generateSitemaps](https://nextjs.org/docs/app/api-reference/functions/generate-sitemaps)の翻訳
Closes #39 
[generateSitemaps _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14254809/generateSitemaps._.Next.js.pdf)
=> Docs: Translate generateSitemaps

docs/app-router/01-building-your-application/07-configuring/04-absolute-imports-and-module-aliases.md
[Absolute Imports and Module Path Aliases](https://nextjs.org/docs/app/building-your-application/configuring/absolute-imports-and-module-aliases)の翻訳
closes #88
=> #88 configuring/absolute-imports-and-module-aliases

docs/app-router/03-architecture/turbopack.md
[Turbopack](https://nextjs.org/docs/architecture/turbopack)の翻訳
Closes #68 
[Turbopack _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14357127/Turbopack._.Next.js.pdf)
=> Docs: Translate Architecture / Turbopack

docs/app-router/02-api-reference/04-next-config-js/exportPathMap.md
[exportPathMap](https://nextjs.org/docs/app/api-reference/next-config-js/exportPathMap)の翻訳
Closes #51 
[exportPathMap (Deprecated) _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14339079/exportPathMap.Deprecated._.Next.js.pdf)
=> Docs: Translate next.config.js Options / exportPathMap

docs/app-router/02-api-reference/04-next-config-js/headers.md
[headers](https://nextjs.org/docs/app/api-reference/next-config-js/headers)の翻訳
Closes #52 
[headers _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14343164/headers._.Next.js.pdf)
=> Docs: Translate next.config.js Options / headers page

docs/app-router/02-api-reference/04-next-config-js/redirects.md
[redirects ](https://nextjs.org/docs/app/api-reference/next-config-js/redirects )の翻訳
Closes #59  
[redirects _ Next.js 公式ドキュメント 日本語翻訳プロジェクト.pdf](https://github.com/openstandia/Nextjs-docs-ja/files/14343333/redirects._.Next.js.pdf)
=> Docs: Translate next.config.js Options / redirects page 

vercel.json
昔の/docs/app-router/* のアクセスがリンク切れでご迷惑をおかけするので、できるだけ互換性を持たせるようにしました。
https://github.com/openstandia/Nextjs-docs-ja/issues/245
=> add redirects for compatibility

.github/workflows/close-issues-bot.yml
issueが溜まることを防ぐため、一定期間更新のない非アクティブなissueを自動でクローズするbotをGithub Actionsに追加した。
close #259
=> feat: Add close issue bot

scripts/konjacbot/pr.mts, scripts/konjacbot/translate.mts, scripts/konjacbot/utils.mts
翻訳結果のブレを少なくするためにChatGPT APIのオプションに`temperature = 0`のオプションを追加した。
=> feat: Add temperature option to OpenAI API

scripts/konjacbot/dlimg.mts
konjacbotが失敗している問題の対応
https://github.com/openstandia/Nextjs-docs-ja/actions/runs/14025990219/job/39264647626
画像のダウンロードURLが変更されていたため。画像取得先を以下のような形式に変更
https://nextjs.org/_next/image?url=https%3A%2F%2Fh8DxKfmAPhn8O0p3.public.blob.vercel-storage.com%2Fdocs%2Fdark%2Ftypescript-command-palette.png&w=1920&q=75
GitHubAction：https://github.com/openstandia/Nextjs-docs-ja/actions/runs/14028666757
PR：https://github.com/openstandia/Nextjs-docs-ja/pull/371
=> chore: fix image download (#369)
